### ISSUE TITLE
Min scale is not considerated in game

### ISSUE THREAD

**Issue by Naurk** [ozzr/godot_terrain#14]
Minimum scale is not considerated when I run the game, but is considerated in the editor. I find out this while testing a TREE, I do not tested other combinations.
Here is the video in the editor where I set min and max scale with the same values to make it more clear:
https://user-images.githubusercontent.com/57441396/216953041-9ae4586e-8072-44c8-a339-aef08d0dc5a1.mp4

Here when I run the scene:
https://user-images.githubusercontent.com/57441396/216953130-b7779e34-022a-44c7-b902-521177f4b14c.mp4

**Comment by ozzr** [comment]
Hi!, thanks for opening an issue. I am going to take a look at it right now

**Comment by ozzr** [comment]
Interesting ....

![biome rendering issue](https://user-images.githubusercontent.com/36895302/217162888-289957d8-21e9-4267-85cd-4197a805b022.png)
In Game (bottom Left) - In Editor (Center Screen)

I managed to replicate the issue
I am checking the BiomeItem class code to find where might be the storage issue

**Comment by ozzr** [comment]
**FIXED!**
![biome rendering issue - FIXED](https://user-images.githubusercontent.com/36895302/217167455-4e74adab-c051-40f0-9412-537df3e1f0f4.png)

Issue at: biome_item.cpp line 305  at:
```` c++ 
static inline void _assign_range_value(int index, Vector3 v, BiomeItem::Range<Vector3> &r)
````

**Comment by ozzr** [comment]
An editor binary with this fix is available at the release section.
