### ISSUE TITLE
Indefinitely increasing vertex count when editing biome items ( version rc1)

### ISSUE THREAD

**Issue by outobugi** [ozzr/godot_terrain#2]
When editing biome item's _float type_ properties, vertex count keeps increasing and fps drops.
Objects drawn and draw calls don't seem to correlate with vertex count. Very weird.

This happens only when dragging the float slider! Directly typing the value doesn't cause the problem.

**Comment by ozzr** [comment]
Mmm, interesting, wich slider is that? What property?

**Comment by outobugi** [comment]
All that makes a draw/update request, I think. I tried density, spawn probability and ground alignment.

**Comment by ozzr** [comment]
Could you try disabling multithreaded in the Grid Renderer please? Tell me is it persists

**Comment by ozzr** [comment]
Oh!!! Also, what version are you using? The last version solved an issue just like that one, please if you are using the rc version  update to the first stable version

[make sure you are using this release](https://github.com/ozzr/godot_terrain/releases/download/v1.0.0-stable/godot_v3.5.1-stable_win64-terrain_v1.0.0.exe)

**Comment by outobugi** [comment]
Hah! Seems like this is fixed in the new one! I hadn't noticed you had updated it already.

**Comment by ozzr** [comment]
Yeah, that one was an annoying bug. It gave me headaches because the vertex count didn't changed despite the huge fps drop down. The issue was that I was storing old tiles generation jobs in the thread pool.

Closing this issue since it is fixed in the new stable release
