### ISSUE TITLE
Biome item changes do not update correctly

### ISSUE THREAD

**Issue by outobugi** [ozzr/godot_terrain#3]
Last time I reported the bug that kept updating the biome items forever and now it's the opposite.
Terrain does not update right away when changing the item density, spawn probability or seed. 
Sometimes the update happens suddenly after a while and sometimes instantly but nothing actually seems to change.
Closing and re-opening the scene does not force the update.

Is there some kind of update queue?
**I change one thing > I change it back > first update happens**
That would explain why the updating feels kinda broken.

**Comment by ozzr** [comment]
Greetings!!! In fact this is not an issue, what happens is that the biome item generates the default spawn positions  in a thread and schedules new changes in the background, usually the late update comes when setting a footprint < 1.0. However, I will try to speed it up

**Comment by ozzr** [comment]
The spawn points are generated using a Poisson Disc Sampling wich takes some time to calculate as it requires about 20 or 30 iterations for every point to find the correct neighbor. There is a PoissonGenerator class you can test it from GDSCRIPT

**Comment by outobugi** [comment]
> usually the late update comes when setting a footprint < 1.0

Okay. That's good to know. I did notice the footprint had something to do with this.

Maybe there should be a progress bar somewhere? Even with faster generation speeds, it may look like a bug to users if there is no visible indicator of a process happening.

**Comment by ozzr** [comment]
Noted. If I don't find a way to solve the generation speed I will add a progress bar for when setting really low values
