### ISSUE TITLE
Biome update latency after painting

### ISSUE THREAD

**Issue by outobugi** [ozzr/godot_terrain#4]
After painting a biome, there is either a big update latency or it won't update at all and can be forced to update by painting a different area or zooming way out and back in. 

The cause of this is most likely the same as described in #3

**Comment by ozzr** [comment]
This issue is most probably the same as the [previous one](https://github.com/ozzr/godot_terrain/issues/3), however I will check the code, to see how to speed things up a little

**Comment by ozzr** [comment]
The issue is created due to the time the PoissonGenerator takes for generating the default set of points with footprints lower than 1.0. This is a problem of the algorithm itself.
