### ISSUE TITLE
Terrain painting locked after switch from Texture to Heightmap painting

### ISSUE THREAD

**Issue by outobugi** [ozzr/godot_terrain#5]
Happens with EXTENDED_16 splatmap mode.

Steps to reproduce:
1. Paint textures
2. Switch to any heightmap tool and paint
3. Change back to texture painting

**Comment by ozzr** [comment]
Already found the culprit. The Error happens when using the EXTENDED_16 Paint Mode and it is due to an internal mutex in the TerrainTool class staying in locked state. 
Added into the next release.
